#index:
#    path: /admin
#    controller: App\Controller\AdminController::addGame

admin:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: add_game
        permanent: true
        keepQueryParams: true